# Default values for cinder.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  image_repository: DEFINED-IN-REGION-CHART
  image_namespace: DEFINED-IN-REGION-CHART
  cinder_api_port_internal: '8776'

  hypervisors_vmware:
    - name: DEFINED-IN-REGION-CHART
      username: DEFINED-IN-REGION-CHART
      password: DEFINED-IN-REGION-CHART
      host: DEFINED-IN-REGION-CHART
      availability_zone: DEFINED-IN-REGION-CHART
  volumes_netapp:
    - name: DEFINED-IN-REGION-CHART
      username: DEFINED-IN-REGION-CHART
      password: DEFINED-IN-REGION-CHART
      host: DEFINED-IN-REGION-CHART
      vserver: DEFINED-IN-REGION-CHART
      availability_zone: DEFINED-IN-REGION-CHART

image_version_cinder_api_m3: 'v1'
image_version_cinder_scheduler: 'v1'
image_version_cinder_volume: 'v1'

debug: "True"

db_name: cinder
db_user: cinder
db_password: DEFINED-IN-REGION-CHART

port_metrics: '9102'

sentry_dsn_key: DEFINE-IN-REGION-CHART




postgres:
  name: cinder

logging:
    formatters:
        context:
            class: oslo_log.formatters.ContextFormatter
        default:
            format: "%(message)s"
    handlers:
        stdout:
            class: StreamHandler
            args: "(sys.stdout,)"
            formatter: context
        "null":
            class: logging.NullHandler
            args: "()"
            formatter: default
        sentry:
            class: raven.handlers.logging.SentryHandler
            level: ERROR
            args: "()"
    loggers:
        root:
            handlers: "null"
            level: WARNING
        cinder:
            handlers: stdout, sentry
            level: INFO
        taskflow:
            handlers: stdout, sentry
            level: INFO
        cinder.flow_utils:
            handlers: stdout, sentry
            level: INFO
        oslo_vmware:
            handlers: stdout, sentry
            level: DEBUG
        amqp:
            handlers: stdout, sentry
        amqplib:
            handlers: stdout, sentry
        boto:
            handlers: stdout, sentry
        eventlet.wsgi.server:
            handlers: stdout, sentry
            level: INFO
        sqlalchemy:
            handlers: stdout, sentry
        suds:
            handlers: stdout, sentry
