apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-bin
  labels:
    system: openstack
    type: configuration
    component: glance

data:
  glance-api-start: |
{{ include "bin/glance-api-start" .| indent 4 }}
  glance-registry-start: |
{{ include "bin/glance-registry-start" .| indent 4 }}
  common.sh: |
{{ include "common.sh" .| indent 4 }}



