apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-bin
  labels:
    system: openstack
    type: configuration
    component: glance

data:
  db-migrate: |
{{ .Files.Get "bin/db-migrate" | indent 4 }}
  common.sh: |
{{ include "common.sh" .| indent 4 }}



