apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-etc
  labels:
    system: openstack
    type: configuration
    component: glance

data:
  glance-api.conf: |
{{ tuple "etc/_glance-api.conf.tpl" . | include "template" | indent 4 }}
  glance-registry.conf: |
{{ tuple "etc/_glance-registry.conf.tpl" . | include "template" | indent 4 }}
  swift-store.conf: |
{{ tuple "etc/_swift-store.conf.tpl" . | include "template" | indent 4 }}
  policy.json: |
{{ tuple "etc/_glance-policy.json.tpl" . | include "template" | indent 4 }}
  logging.conf: |
{{ include "loggerIni" .Values.logging | indent 4 }}
  glance-api-paste.ini: |
{{ tuple "etc/_glance-api-paste.ini.tpl" . | include "template" | indent 4 }}
  config.json: |
    {"command": "kubernetes-entrypoint",
       "config_files":[
           {"source": "/var/lib/kolla/config_files/glance-api.conf", "dest": "/etc/glance/glance-api.conf", "owner": "glance", "perm": "0400"},
           {"source": "/var/lib/kolla/config_files/glance-registry.conf", "dest": "/etc/glance/glance-registry.conf", "owner": "glance", "perm": "0400"},
           {"source": "/var/lib/kolla/config_files/swift-store.conf", "dest": "/etc/glance/swift-store.conf", "owner": "glance", "perm": "0400"},
           {"source": "/var/lib/kolla/config_files/policy.json", "dest": "/etc/glance/policy.json", "owner": "glance", "perm": "0400"},
           {"source": "/var/lib/kolla/config_files/glance-api-paste.ini", "dest": "/etc/glance/glance-api-paste.ini", "owner": "glance", "perm": "0400"},
           {"source": "/var/lib/kolla/config_files/logging.conf", "dest": "/etc/glance/logging.conf", "owner": "glance", "perm": "0400"}
       ]
    }
