apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-etc
  labels:
    system: openstack
    type: configuration
    component: glance

data:
  glance-api.conf: |
{{ include "etc/glance-api.conf" .| indent 4 }}
  glance-registry.conf: |
{{ include "etc/glance-registry.conf" .| indent 4 }}
  swift-store.conf: |
{{ include "etc/swift-store.conf" .| indent 4 }}
  logging.conf: |
{{ include "etc/glance-logging.conf" .| indent 4 }}
  policy.json: |
{{ include "etc/glance-policy.json" .| indent 4 }}

