apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-etc
  labels:
    system: openstack
    type: configuration
    component: glance

data:
  glance-api.conf: |
{{ tuple "etc/_glance-api.conf.tpl" . | include "template" | indent 4 }}
  glance-registry.conf: |
{{ tuple "etc/_glance-registry.conf.tpl" . | include "template" | indent 4 }}
  swift-store.conf: |
{{ tuple "etc/_swift-store.conf.tpl" . | include "template" | indent 4 }}
  policy.json: |
{{ tuple "etc/_glance-policy.json.tpl" . | include "template" | indent 4 }}
  logging.conf: |
{{ include "loggerIni" .Values.logging | indent 4 }}
  glance-api-paste.ini: |
{{ tuple "etc/_glance-api-paste.ini.tpl" . | include "template" | indent 4 }}
