apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-patches
  labels:
    system: openstack
    type: patches
    component: neutron

data:
  connection-manager.patch: |
{{ .Files.Get "patches/connection_manager.diff" | indent 4 }}
