kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: barbican-api
  labels:
    system: openstack
    type: api
    component: barbican
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: barbican-api
  template:
    metadata:
      labels:
        name: barbican-api
      annotations:
        chart-version: {{.Chart.Version}}
    spec:
      containers:
        - name: barbican-api
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-barbican-m3:{{.Values.image_version_barbican_m3}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /container.init/barbican-api-start"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "postgres-barbican,rabbitmq"
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.global.barbican_api_port_internal}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          ports:
            - name: barbican-api
              containerPort: {{.Values.global.barbican_api_port_internal}}
          volumeMounts:
            - mountPath: /barbican-etc
              name: barbican-etc
            - mountPath: /barbican-patches
              name: barbican-patches
            - mountPath: /container.init
              name: container-init

      volumes:
        - name: barbican-etc
          configMap:
            name: barbican-etc
        - name: barbican-patches
          configMap:
            name: barbican-patches
        - name: container-init
          configMap:
            name: barbican-bin
