apiVersion: v1
kind: ConfigMap
metadata:
  name: barbican-etc
  labels:
    system: openstack
    type: configuration
    component: barbican

data:
  barbican-api-paste.ini: |
{{ tuple "etc/_barbican-api-paste.ini.tpl" . | include "template" | indent 4 }}
  barbican.conf: |
{{ tuple "etc/_barbican.conf.tpl" . | include "template" | indent 4 }}
  policy.json: |
{{ tuple "etc/_policy.json.tpl" . | include "template" | indent 4 }}
