apiVersion: v1
kind: ConfigMap
metadata:
  name: barbican-etc
  labels:
    system: openstack
    type: configuration
    component: barbican

data:
  barbican-api-paste.ini: |
{{ include "barbican/templates/etc/_barbican-api-paste.ini.tpl" .| indent 4 }}
  barbican.conf: |
{{ include "barbican/templates/etc/_barbican.conf.tpl" .| indent 4 }}
