apiVersion: v1
kind: ConfigMap
metadata:
  name: barbican-patches
  labels:
    system: openstack
    type: patches
    component: barbican

data:
  barbican-api.diff: |
{{ .Files.Get "patches/barbican-api.diff" | indent 4 }}
  consumers.diff: |
{{ .Files.Get "patches/consumers.diff" | indent 4 }}


