# Default values for horizon.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
#
global:
  image_repository: REQUIRED
  image_namespace: REQUIRED
  configuration_repository: REQUIRED
  configuration_revision: REQUIRED

image_version_horizon_m3: REQUIRED

secret_key: DEFINED-IN-REGION-CHART
