{{- if .Values.image_version_ironic_conductor -}}
kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: ironic-conductor
  labels:
    system: openstack
    type: backend
    component: ironic
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: ironic-conductor
  template:
    metadata:
      labels:
        name: ironic-conductor
    spec:
      containers:
        - name: ironic-conductor
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-ironic-conductor:{{.Values.image_version_ironic_conductor}}
          imagePullPolicy: IfNotPresent
          command:
            - kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "ironic-conductor --config-file /etc/ironic/ironic.conf"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "ironic-api,rabbitmq"
          volumeMounts:
            - mountPath: /etc/ironic
              name: etcironic
            - mountPath: /etc/ironic/ironic.conf
              name: ironic-etc
              subPath: ironic.conf
              readOnly: true
            - mountPath: /etc/ironic/policy.json
              name: ironic-etc
              subPath: policy.json
              readOnly: true
            - mountPath: /etc/ironic/rootwrap.conf
              name: ironic-etc
              subPath: rootwrap.conf
              readOnly: true
            - mountPath: /etc/ironic/logging.conf
              name: ironic-etc
              subPath: logging.conf
              readOnly: true
            - mountPath: /tftpboot
              name: ironic-tftp
        - name: ironic-pxe
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-ironic-pxe:{{.Values.image_version_ironic_pxe}}
          imagePullPolicy: IfNotPresent
          command: ["ptftpd", "-v", "-d", "/tftpmap.py:handle", "eth0", "/tftpboot"]
          ports:
            - name: ironic-pxe
              protocol: UDP
              containerPort: {{.Values.global.ironic_pxe_port_public}}
          volumeMounts:
            - mountPath: /tftpboot
              name: ironic-tftp
        - name: ironic-ipxe
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-ironic-conductor:{{.Values.image_version_ironic_conductor}}
          imagePullPolicy: IfNotPresent
          workingDir: /tftpboot
          command: ["python", "-m", "SimpleHTTPServer", "{{.Values.conductor.deploy.port}}"]
          ports:
            - name: ironic-ipxe
              protocol: TCP
              containerPort: {{.Values.conductor.deploy.port}}
          volumeMounts:
            - mountPath: /tftpboot
              name: ironic-tftp
      volumes:
        - name: etcironic
          emptyDir: {}
        - name: ironic-etc
          configMap:
            name: ironic-etc
        - name: ironic-tftp
          persistentVolumeClaim:
            claimName: ironic-tftp-pvclaim
{{ end -}}
