{{- if .Values.global.ironic_tftp_ip -}}
kind: Service
apiVersion: v1

metadata:
  name: ironic-pxe
  labels:
    system: openstack
    type: backend
    component: ironic
spec:
  type: NodePort
  selector:
    name: ironic-conductor
  ports:
    - name: ironic-pxe
      protocol: UDP
      port: {{.Values.global.ironic_tftp_port_public}}
    - name: ironic-ipxe
      protocol: TCP
      port: {{.Values.conductor.deploy.port}}
  externalIPs:
    - {{.Values.global.ironic_tftp_ip}}
  sessionAffinity: "ClientIP"
{{ end -}}
