apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-etc
  labels:
    system: openstack
    type: configuration
    component: ironic

data:
  ironic.conf: |
{{ include "ironic/templates/etc/_ironic.conf.tpl" .| indent 4 }}
