apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-etc
  labels:
    system: openstack
    type: configuration
    component: ironic

data:
  ironic.conf: |
{{ tuple "etc/_ironic.conf.tpl" . | include "template" | indent 4 }}

