{{- if or .Values.image_version_ironic_api .Values.image_version_ironic_conductor -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-etc
  labels:
    system: openstack
    type: configuration
    component: ironic

data:
  config.json: |
    {"command": "kubernetes-entrypoint"}
  ironic.conf: |
{{ include (print .Template.BasePath "/etc/_ironic.conf.tpl") . | indent 4 }}
  logging.conf: |
{{ include "loggerIni" .Values.logging | indent 4 }}
{{ end -}}
