apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-etc
  labels:
    system: openstack
    type: configuration
    component: ironic

data:
  ironic.conf: |
{{ include "etc/ironic.conf" .| indent 4 }}
