kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: ironic-inspector
  labels:
    system: openstack
    type: backend
    component: none
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: ironic-inspector
  template:
    metadata:
      labels:
        name: ironic-inspector
    spec:
      containers:
        - name: ironic-inspector
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-ironic-inspector:{{.Values.image_version_ironic_inspector}}
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /container.init/ironic-inspector-start"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "ironic-api,rabbitmq"
            - name: DEBUG_CONTAINER
              value: "false"
          volumeMounts:
            - mountPath: /ironic-etc
              name: ironic-etc
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: ironic-etc
          configMap:
            name: ironic-etc
        - name: container-init
          configMap:
            name: ironic-bin
