{{- if .Values.image_version_ironic_inspector -}}
kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: ironic-inspector
  labels:
    system: openstack
    type: backend
    component: none
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: ironic-inspector
  template:
    metadata:
      labels:
        name: ironic-inspector
    spec:
      containers:
        - name: ironic-inspector
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-ironic-inspector:{{.Values.image_version_ironic_inspector}}
          imagePullPolicy: IfNotPresent
          command:
            - kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "ironic-inspector --config-file /etc/ironic/ironic.conf"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "ironic-api,rabbitmq"
          volumeMounts:
            - mountPath: /etc/ironic
              name: etcironic
            - mountPath: /etc/ironic/ironic.conf
              name: ironic-inspector-etc
              subPath: ironic.conf
              readOnly: true
            - mountPath: /etc/ironic/policy.json
              name: ironic-etc
              subPath: policy.json
              readOnly: true
            - mountPath: /etc/ironic/rootwrap.conf
              name: ironic-etc
              subPath: rootwrap.conf
              readOnly: true
            - mountPath: /etc/ironic/logging.conf
              name: ironic-etc
              subPath: logging.conf
              readOnly: true
{{- if .Values.image_version_staticdhcpd}}
        - name: dhcp
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-staticdhcpd:{{.Values.image_version_staticdhcpd}}
          imagePullPolicy: IfNotPresent
          command:
            - staticDHCPd
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: dhcp
              protocol: UDP
              containerPort: {{.Values.inspector.dhcp.port}}
            - name: dhcp-proxy
              protocol: UDP
              containerPort: {{.Values.inspector.dhcp.proxy_port}}
          volumeMounts:
            - mountPath: /conf
              name: dhcp-config
{{- end }}
      volumes:
        - name: etcironic
          emptyDir: {}
        - name: ironic-etc
          configMap:
            name: ironic-etc
            defaultMode: 0444
        - name: ironic-inspector-etc
          configMap:
            name: ironic-inspector-etc
            defaultMode: 0444
{{- if .Values.image_version_staticdhcpd }}
        - name: dhcp-config
          configMap:
            name: ironic-inspector-dhcp
            defaultMode: 0444
{{ end -}}
{{ end -}}
