apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-patches
  namespace: {{.Release.Namespace}}
  labels:
    system: openstack
    type: patches
    component: ironic

data:
  app.diff: |
{{ include "patches/app.diff" .| indent 4 }}
