apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-patches
  labels:
    system: openstack
    type: patches
    component: ironic

data:
  app.diff: |
{{ .Files.Get "patches/app.diff"| indent 4 }}
