# Default values for neutron.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
debug: "True"

db_name: neutron
db_user: neutron
db_password: DEFINED-IN-REGION-CHART

port_metrics: '9102'

sentry_dsn_key: DEFINE-IN-REGION-CHART

aci_apic_hosts: DEFINED-IN-REGION-CHART
aci_apic_user: DEFINED-IN-REGION-CHART
aci_apic_password: DEFINED-IN-REGION-CHART
aci_apic_tenant_name: DEFINED-IN-REGION-CHART


postgres:
  name: neutron