# Default values for neutron.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  image_namespace: REQUIRED
  image_repository: REQUIRED
  neutron_api_port_admin: '9696'
  neutron_api_port_internal: '9696'
  neutron_api_port_public: '443'

  hypervisors_vmware:
    - name: DEFINED-IN-REGION-CHART
      username: DEFINED-IN-REGION-CHART
      password: DEFINED-IN-REGION-CHART
      host: DEFINED-IN-REGION-CHART
      availability_zone: DEFINED-IN-REGION-CHART
  network_agents:
    - name: DEFINED-IN-REGION-CHART
      node: DEFINED-IN-REGION-CHART

debug: "True"

db_name: neutron
db_user: neutron
db_password: DEFINED-IN-REGION-CHART

port_metrics: '9102'

sentry_dsn_key: DEFINE-IN-REGION-CHART

image_version_neutron_server_m3: DEFINED-IN-REGION-CHART
image_version_neutron_dhcp_agent: DEFINED-IN-REGION-CHART
image_version_neutron_metadata_agent: DEFINED-IN-REGION-CHART
image_version_neutron_l3_agent: DEFINED-IN-REGION-CHART
image_version_neutron_openvswitch_agent: DEFINED-IN-REGION-CHART
image_version_neutron_vswitchdb: DEFINED-IN-REGION-CHART
image_version_neutron_vswitchd: DEFINED-IN-REGION-CHART

logging:
    formatters:
        context:
            class: oslo_log.formatters.ContextFormatter
        default:
            format: "%(message)s"
    handlers:
        stderr:
            class: StreamHandler
            args: "(sys.stderr,)"
            formatter: context
        stdout:
            class: StreamHandler
            args: "(sys.stdout,)"
        "null":
            class: logging.NullHandler
            formatter: default
            args: "()"
        sentry:
            class: "raven.handlers.logging.SentryHandler"
            level: ERROR
            args: "()"
    loggers:
        root:
            handlers: "null"
            level: WARNING
        neutron:
            handlers: stdout, sentry
            level: DEBUG
        neutron_lbaas:
            handlers: stdout, sentry
            level: DEBUG
        amqp:
            handlers: stdout, sentry
        amqplib:
            handlers: stdout, sentry
        sqlalchemy:
            handlers: stdout, sentry
        boto:
            handlers: stdout, sentry
        suds:
            handlers: stdout, sentry
            level: INFO
        eventlet.wsgi.server:
            handlers: stdout, sentry
            level: INFO
        networking_aci:
            handlers: stdout, sentry
            level: DEBUG
        networking_cisco:
            handlers: stdout, sentry
            level: DEBUG
        networking_arista:
            handlers: stdout, sentry
            level: DEBUG
        f5lbaasdriver:
            handlers: stdout, sentry
            level: DEBUG
        f5_openstack_agent:
            handlers: stdout, sentry
            level: DEBUG
        networking_f5_ml2:
            handlers: stdout, sentry
            level: DEBUG

postgres:
  name: neutron
