# Default values for neutron.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  image_namespace: REQUIRED
  image_repository: REQUIRED
  neutron_api_port_admin: '9696'
  neutron_api_port_internal: '9696'
  neutron_api_port_public: '443'


debug: "True"

db_name: neutron
db_user: neutron
db_password: DEFINED-IN-REGION-CHART

port_metrics: '9102'

sentry_dsn_key: DEFINE-IN-REGION-CHART

aci_apic_hosts: DEFINED-IN-REGION-CHART
aci_apic_user: DEFINED-IN-REGION-CHART
aci_apic_password: DEFINED-IN-REGION-CHART
aci_apic_tenant_name: DEFINED-IN-REGION-CHART

image_version_neutron_server_m3: DEFINED-IN-REGION-CHART
image_version_neutron_openvswitch_agent: DEFINED-IN-REGION-CHART
image_version_neutron_vswitchdb: DEFINED-IN-REGION-CHART
image_version_neutron_vswitchd: DEFINED-IN-REGION-CHART

loggers_keys: 'root, neutron'

postgres:
  name: neutron
