apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-bin
  labels:
    system: openstack
    type: configuration
    component: keystone

data:
  common.sh: |
{{ include "common.sh" .| indent 4 }}
  keystone-bootstrap: |
{{ include (print .Template.BasePath "/bin/_keystone-bootstrap.tpl") . | indent 4 }}
  keystone-seed: |
{{ include (print .Template.BasePath "/bin/_keystone-seed.tpl") . | indent 4 }}
  keystone-start: |
{{ include (print .Template.BasePath "/bin/_keystone-start.tpl") . | indent 4 }}
  db-migrate: |
{{ include (print .Template.BasePath "/bin/_db-migrate.tpl") . | indent 4 }}
  keystone-cron: |
{{ include (print .Template.BasePath "/bin/_keystone-cron.tpl") . | indent 4 }}
  repair_assignments: |
{{ include (print .Template.BasePath "/bin/_repair_assignments.tpl") . | indent 4 }}
