kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: keystone
  labels:
    system: openstack
    type: api
    component: keystone
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  selector:
    matchLabels:
      name: keystone


  template:
    metadata:
      labels:
        name: keystone
      annotations:
        chart-version: {{.Chart.Version}}
    spec:
      nodeSelector:
        zone: farm
      containers:
        - name: keystone
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-keystone-m3:{{.Values.image_version_keystone_m3}}
          imagePullPolicy: IfNotPresent
          command:
            - /openstack-kube/openstack-kube/scripts/_container_init
          args:
            - keystone-start
          livenessProbe:
            httpGet:
              path: /v3
              port: 5000
            initialDelaySeconds: 15
            timeoutSeconds: 15
          env:
            - name: DEBUG_CONTAINER
              value: "false"
            - name: SENTRY_DSN
              value: "{{ include "sentry_dsn_keystone" . }}"
            - name: STATSD_HOST
              value: "localhost"
            - name: STATSD_PORT
              value: "9125"
          ports:
            - name: public
              containerPort: 5000
            - name: admin
              containerPort: 35357
          volumeMounts:
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /keystone-etc
              name: keystone-etc
            - mountPath: /fernet-keys
              name: fernet-secret
              readOnly: true
            - mountPath: /container.init
              name: container-init
        - name: statsd
          image: prom/statsd-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: metrics
              containerPort: {{.Values.port_metrics}}
      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{.Values.global.configuration_repository}}
            revision: {{.Values.global.configuration_revision}}
        - name: keystone-etc
          configMap:
            name: keystone-etc
        - name: fernet-secret
          secret:
            secretName: fernet-secret
        - name: container-init
          configMap:
            name: keystone-bin
