apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-etc
  labels:
    system: openstack
    type: configuration
    component: keystone

data:
  keystone.conf: |
{{ include "keystone/templates/etc/_keystone.conf.tpl" .| indent 4 }}
  policyv3.json: |
{{ include "keystone/templates/etc/_keystone-policyv3.json.tpl" .| indent 4 }}
  wsgi-keystone.conf: |
{{ include "keystone/templates/etc/wsgi-_keystone.conf.tpl" .| indent 4 }}
