apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-etc
  labels:
    system: openstack
    type: configuration
    component: keystone

data:
  keystone.conf: |
{{ tuple "etc/_keystone.conf.tpl" . | include "template" | indent 4 }}
  policyv3.json: |
{{ tuple "etc/_keystone-policyv3.json.tpl" . | include "template" | indent 4 }}
  wsgi-keystone.conf: |
{{ tuple "etc/_wsgi-keystone.conf.tpl" . | include "template" | indent 4 }}

