apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-etc
  labels:
    system: openstack
    type: configuration
    component: keystone

data:
  keystone.conf: |
{{ include (print .Template.BasePath "/etc/_keystone.conf.tpl") . | indent 4 }}
  policyv3.json: |
{{ include (print .Template.BasePath "/etc/_keystone-policyv3.json.tpl") . | indent 4 }}
  wsgi-keystone.conf: |
{{ include (print .Template.BasePath "/etc/_wsgi-keystone.conf.tpl") . | indent 4 }}

