kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: cinder-api
  labels:
    system: openstack
    type: api
    component: cinder
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: cinder-api
  template:
    metadata:
      labels:
        name: cinder-api
    spec:
      containers:
        - name: cinder-api
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-cinder-api-m3:{{.Values.image_version_cinder_api_m3}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /container.init/cinder-api-start"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_JOBS
              value: "cinder-migration"
            - name: DEPENDENCY_SERVICE
              value: "postgres-cinder,rabbitmq"
            - name: DEBUG_CONTAINER
              value: "false"
            - name: STATSD_HOST
              value: "localhost"
            - name: STATSD_PORT
              value: "9125"
            - name: SENTRY_DSN
              value: {{ include "sentry_dsn_cinder" . | quote}}
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.global.cinder_api_port_internal}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          ports:
            - name: cinder-api
              containerPort: {{.Values.global.cinder_api_port_internal}}
          volumeMounts:
            - mountPath: /cinder-etc
              name: cinder-etc
            - mountPath: /container.init
              name: container-init
        - name: statsd
          image: prom/statsd-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: metrics
              containerPort: {{.Values.port_metrics}}
      volumes:
        - name: cinder-etc
          configMap:
            name: cinder-etc
        - name: container-init
          configMap:
            name: cinder-bin
