apiVersion: v1
kind: ConfigMap
metadata:
  name: cinder-bin
  labels:
    system: openstack
    type: configuration
    component: cinder

data:
  cinder-api-start: |
{{ include "bin/cinder-api-start" .| indent 4 }}
  cinder-scheduler-start: |
{{ include "bin/cinder-scheduler-start" .| indent 4 }}
  cinder-volume-start: |
{{ include "bin/cinder-volume-start" .| indent 4 }}
  common.sh: |
{{ include "common.sh" .| indent 4 }}



