apiVersion: v1
kind: ConfigMap
metadata:
  name: cinder-bin
  labels:
    system: openstack
    type: configuration
    component: cinder

data:
  db-migrate: |
{{ .Files.Get "bin/db-migrate" | indent 4 }}

  common.sh: |
{{ include "common.sh" .| indent 4 }}
