apiVersion: v1
kind: ConfigMap
metadata:
  name: cinder-etc
  labels:
    system: openstack
    type: configuration
    component: cinder

data:
  cinder.conf: |
{{ include "cinder/templates/etc/_cinder.conf.tpl" .| indent 4 }}
  logging.conf: |
{{ include "cinder/templates/etc/_cinder-logging.conf.tpl" .| indent 4 }}
