apiVersion: v1
kind: ConfigMap
metadata:
  name: cinder-etc
  labels:
    system: openstack
    type: configuration
    component: cinder

data:
  api-paste.ini: |
{{ include (print $.Template.BasePath "/etc/_api-paste.ini.tpl") . | indent 4 }}
  cinder.conf: |
{{ include (print $.Template.BasePath "/etc/_cinder.conf.tpl") . | indent 4 }}
  policy.json: |
{{ include (print $.Template.BasePath "/etc/_cinder-policy.json.tpl") . | indent 4 }}
  logging.conf: |
{{ include "loggerIni" .Values.logging | indent 4 }}
  config.json: |
    {"command": "kubernetes-entrypoint",
       "config_files":[
           {"source": "/var/lib/kolla/config_files/api-paste.ini", "dest": "/etc/cinder/api-paste.ini", "owner": "cinder", "perm": "0400"},
           {"source": "/var/lib/kolla/config_files/cinder.conf", "dest": "/etc/cinder/cinder.conf", "owner": "cinder", "perm": "0400"},
           {"source": "/var/lib/kolla/config_files/policy.json", "dest": "/etc/cinder/policy.json", "owner": "cinder", "perm": "0400"},
           {"source": "/var/lib/kolla/config_files/logging.conf", "dest": "/etc/cinder/logging.conf", "owner": "cinder", "perm": "0400"}
       ]
    }
