apiVersion: v1
kind: ConfigMap
metadata:
  name: cinder-etc
  labels:
    system: openstack
    type: configuration
    component: cinder

data:
  cinder.conf: |
{{ tuple "etc/_cinder.conf.tpl" . | include "template" | indent 4 }}
  logging.conf: |
{{ tuple "etc/_cinder-logging.conf.tpl" . | include "template" | indent 4 }}

