kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: cinder-scheduler
  labels:
    system: openstack
    type: backend
    component: cinder
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: cinder-scheduler
  template:
    metadata:
      labels:
        name: cinder-scheduler
    spec:
      containers:
        - name: cinder-scheduler
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-cinder-scheduler:{{.Values.image_version_cinder_scheduler}}
          imagePullPolicy: IfNotPresent
          command:
            - bash
          args:
            - /container.init/cinder-scheduler-start
          env:
            - name: DEBUG_CONTAINER
              value: "false"
            - name: SENTRY_DSN
              value: {{ include "sentry_dsn_cinder" . | quote}}
          volumeMounts:
            - mountPath: /development
              name: development
            - mountPath: /cinder-etc
              name: cinder-etc
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: cinder-etc
          configMap:
            name: cinder-etc
        - name: development
          persistentVolumeClaim:
            claimName: development-pvclaim
        - name: container-init
          configMap:
            name: cinder-bin
