kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: designate-api
  labels:
    system: openstack
    type: api
    component: designate
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      app: designate-api
  template:
    metadata:
      labels:
        app: designate-api
      annotations:
        chart-version: {{.Chart.Version}}
    spec:
      nodeSelector:
        zone: farm
      containers:
        - name: designate-api
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-designate-api-m3:{{.Values.image_version_designate_api_m3}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - /openstack-kube/openstack-kube/scripts/_container_init
          args:
            - designate-api-start
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.global.designate_api_port_internal}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          env:
            - name: DEBUG_CONTAINER
              value: "false"
            - name: STATSD_HOST
              value: "localhost"
            - name: STATSD_PORT
              value: "9125"
            - name: SENTRY_DSN
              value: {{include "sentry_dsn_designate" . | quote}}
          ports:
            - name: designate-api
              containerPort: {{.Values.global.designate_api_port_internal}}
          volumeMounts:
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /designate-etc
              name: designate-etc
            - mountPath: /container.init
              name: container-init
        - name: statsd
          image: prom/statsd-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: metrics
              containerPort: {{.Values.global.designate_metrics_port}} 
      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{ .Values.global.configuration_repository }} 
            revision: {{ .Values.global.configuration_revision }}
        - name: designate-etc
          configMap:
            name: designate-etc
        - name: container-init
          configMap:
            name: designate-bin
