apiVersion: v1
kind: ConfigMap
metadata:
  name: designate-bin
  labels:
    system: openstack
    type: configuration
    component: designate
data:
  designate-api-start: |
{{ .Files.Get "bin/designate-api-start" | indent 4 }}
  designate-central-start: |
{{ .Files.Get "bin/designate-central-start" | indent 4 }}
  designate-mdns-start: |
{{ .Files.Get "bin/designate-mdns-start" | indent 4 }}
  designate-poolmanager-start: |
{{ .Files.Get "bin/designate-poolmanager-start" | indent 4 }}
  common.sh: |
{{ include "common.sh" . | indent 4}}
