kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: designate-central
  labels:
    system: openstack
    type: backend
    component: designate
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      app: designate-central
  template:
    metadata:
      labels:
        app: designate-central
      annotations:
        chart-version: {{.Chart.Version}}
    spec:
      containers:
        - name: designate-central
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-designate-central-m3:{{.Values.image_version_designate_central_m3}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /container.init/designate-central-start"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_JOBS
              value: "designate-migration"
            - name: DEPENDENCY_SERVICE
              value: "designate-mariadb,rabbitmq"
            - name: DEBUG_CONTAINER
              value: "false"
            - name: SENTRY_DSN
              value: {{.Values.sentry_dsn | quote}}
          volumeMounts:
            - mountPath: /designate-etc
              name: designate-etc
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: designate-etc
          configMap:
            name: designate-etc
        - name: container-init
          configMap:
            name: designate-bin
