kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: designate-central
  labels:
    system: openstack
    type: backend
    component: designate
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      app: designate-central
  template:
    metadata:
      labels:
        app: designate-central
      annotations:
        chart-version: {{.Chart.Version}}
    spec:
      nodeSelector:
        zone: farm
      containers:
        - name: designate-central
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-designate-central-m3:{{.Values.global.image_version_designate_central_m3}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - /openstack-kube/openstack-kube/scripts/_container_init
          args:
            - designate-central-start
          env:
            - name: DEBUG_CONTAINER
              value: "false"
            - name: SENTRY_DSN
              value: {{include "sentry_dsn_designate" . | quote}}
          volumeMounts:
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /designate-etc
              name: designate-etc
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{.Values.global.configuration_repository}}
            revision: {{.Values.global.configuration_revision}}
        - name: designate-etc
          configMap:
            name: designate-etc
        - name: container-init
          configMap:
            name: designate-bin
