apiVersion: v1
kind: ConfigMap
metadata:
  name: designate-etc
  labels:
    system: openstack
    type: configuration
    component: designate

data:
  designate.conf: |
{{ include "etc/designate.conf" .| indent 4 }}
  rndc.key: |
{{ include "etc/rndc.key" . | indent 4 }}
  pools.yaml: |
{{ include "etc/pools.yaml" . | indent 4 }}
  policy.json: |
{{ include "etc/designate-policy.json" . | indent 4 }}
  logging.conf: |
{{ include "etc/designate-logging.conf" . | indent 4 }}
