apiVersion: v1
kind: ConfigMap
metadata:
  name: designate-initdb
  labels:
    system: openstack
    type: configuration
    component: designate

data:
  init.sh: |
{{ tuple "initdb/_init.sh.tpl" . | include "template" | indent 4 }}
