kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: designate-mdns
  labels:
    system: openstack
    type: backend
    component: designate
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      app: designate-mdns
  template:
    metadata:
      labels:
        app: designate-mdns
      annotations:
        chart-version: {{.Chart.Version}}
    spec:
      containers:
        - name: designate-mdns
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-designate-mdns-m3:{{.Values.image_version_designate_mdns_m3}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - bash
          args:
            - /container.init/designate-mdns-start
          env:
            - name: DEBUG_CONTAINER
              value: "false"
            - name: SENTRY_DSN
              value: {{.Values.sentry_dsn | quote}}
          livenessProbe:
            tcpSocket:
              port: {{.Values.global.designate_mdns_port_public}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          ports:
            - name: designate-mdns
              containerPort: {{.Values.global.designate_mdns_port_public}}
          volumeMounts:
            - mountPath: /designate-etc
              name: designate-etc
            - mountPath: /container.init
              name: container-init
            - mountPath: /designate-patches
              name: designate-patches
      volumes:
        - name: designate-etc
          configMap:
            name: designate-etc
        - name: container-init
          configMap:
            name: designate-bin
        - name: designate-patches
          configMap:
            name: designate-patches


