apiVersion: v1
kind: ConfigMap
metadata:
  name: hypervisor-kvm
  labels:
    system: openstack
    type: configuration
    component: nova


data:
  hypervisor.conf: |
{{ include "etc/nova/hypervisor-kvm.conf" .| indent 4 }}
  
