apiVersion: v1
kind: ConfigMap
metadata:
  name: hypervisor-vmware
  labels:
    system: openstack
    type: configuration
    component: nova


data:
  hypervisor.conf: |
{{ include "europe-example-region/templates/etc/nova/_hypervisor-vmware.conf.tpl" .| indent 4 }}
