apiVersion: v1
kind: ConfigMap
metadata:
  name: hypervisor-vmware
  namespace: {{.Release.Namespace}}
  labels:
    system: openstack
    type: configuration
    component: nova


data:
  hypervisor.conf: |
{{ include "etc/nova/hypervisor-vmware.conf" .| indent 4 }}
