# Default values for designate.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
#
debug: "True"

sentry_dsn_key: DEFINE-IN-REGION-CHART

global:
  image_repository: DEFINED-IN-OPENSTACK-CHART
  image_namespace: DEFINED-IN-OPENSTACK-CHART
  designate_api_port_internal: DEFINED-IN-OPENSTACK-CHART
  designate_metrics_port: DEFINED-IN-OPENSTACK-CHART 
  designate_mdns_port_public: DEFINED-IN-OPENSTACK-CHART
  designate_mdns_external_ip: DEFINED-IN-REGION-CHART

image_version_designate_api_m3:  DEFINED-IN-REGION-CHART
image_version_designate_central_m3:  DEFINED-IN-REGION-CHART
image_version_designate_mdns_m3:  DEFINED-IN-REGION-CHART
image_version_designate_poolmanager_m3:  DEFINED-IN-REGION-CHART

bind_pools:
  - name: default
    nameservers:
      - hostname: DEFINED-REGION-CHART
        ip:  DEFINED-REGION-CHART
      - hostname: DEFINED-REGION-CHART
        ip:  DEFINED-REGION-CHART
      - hostname: DEFINED-REGION-CHART
        ip:  DEFINED-REGION-CHART

rndc_key: DEFINED-IN-REGION-CHART

poolmanager:
  db_name:  designate_poolmanager
db_name: designate


mariadb:
  name: designate
  initdb_configmap: designate-initdb 
  persistence_claim: db-designate-pvclaim
  


