kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: memcached
  labels:
    system: openstack
    type: cache
    component: memcache
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: memcached
  template:
    metadata:
      labels:
        name: memcached
    spec:
      containers:
        - name: memcached
          image: memcached:1.4.33
          imagePullPolicy: IfNotPresent
          ports:
            - name: memcache
              containerPort: {{.Values.global.memcached_port_public}}
          command: 
            - "memcached"
            - "-m"
            - "4096"
            - "-c"
            - "16384"
        - name: metrics
          image: prom/memcached-exporter:master
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: {{.Values.global.memcached_port_metrics}}

