kind: Service
apiVersion: v1

metadata:
  name: memcached
  labels:
    system: openstack
    component: cache
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{.Values.global.memcached_port_metrics}}"
spec:
  selector:
    name: memcached
  ports:
    - name: memcache
      port: {{.Values.global.memcached_port_public}}
