apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-bin
  labels:
    system: openstack
    type: configuration
    component: nova

data:
  nova-api-start: |
{{ .Files.Get "bin/nova-api-start" | indent 4 }}
  nova-compute-start: |
{{ .Files.Get "bin/nova-compute-start" | indent 4 }}
  nova-conductor-start: |
{{ .Files.Get "bin/nova-conductor-start" | indent 4 }}
  nova-consoleauth-start: |
{{ .Files.Get "bin/nova-consoleauth-start" | indent 4 }}
  nova-libvirt-start: |
{{ .Files.Get "bin/nova-libvirt-start" | indent 4 }}
  nova-novncproxy-start: |
{{ .Files.Get "bin/nova-novncproxy-start" | indent 4 }}
  nova-scheduler-start: |
{{ .Files.Get "bin/nova-scheduler-start" | indent 4 }}
  nova-spicehtml5proxy-start: |
{{ .Files.Get "bin/nova-spicehtml5proxy-start" | indent 4 }}
  nova-virtlog-start: |
{{ .Files.Get "bin/nova-virtlog-start" | indent 4 }}
  common.sh: |
{{ include "common.sh" .| indent 4 }}



