kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: nova-conductor
  labels:
    system: openstack
    type: backend
    component: nova
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: nova-conductor
  template:
    metadata:
      labels:
        name: nova-conductor
    spec:
      containers:
        - name: nova-conductor
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-nova-conductor:{{.Values.image_version_nova_conductor}}
          imagePullPolicy: IfNotPresent
          env:
            - name: COMMAND
              value: "nova-conductor"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "nova-api,rabbitmq"
          volumeMounts:
            - mountPath: /var/lib/kolla/config_files
              name: nova-etc
      volumes:
        - name: nova-etc
          configMap:
            name: nova-etc
