kind: Service
apiVersion: v1

metadata:
  name: nova-console
  labels:
    system: openstack
    type: backend
    component: nova
spec:
  selector:
    name: nova-console

  ports:
    - name: nonvc-proxy
      port: {{.Values.global.nova_novnc_port_public}}
    - name: spicehtml5-proxy
      port: {{.Values.global.nova_spicehtml5_port_public}}
