kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: nova-console
  labels:
    system: openstack
    type: backend
    component: nova
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: nova-console
  template:
    metadata:
      labels:
        name: nova-console
    spec:
      containers:
        - name: nova-consoleauth
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-nova-consoleauth:{{.Values.image_version_nova_consoleauth}}
          imagePullPolicy: IfNotPresent
          env:
            - name: COMMAND
              value: "nova-consoleauth"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "nova-api"
          volumeMounts:
            - mountPath: /var/lib/kolla/config_files
              name: nova-etc
        - name: nova-novncproxy
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-nova-novncproxy:{{.Values.image_version_nova_novncproxy}}
          imagePullPolicy: IfNotPresent
          env:
            - name: COMMAND
              value: "nova-novncproxy"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "nova-api"
          volumeMounts:
            - mountPath: /var/lib/kolla/config_files
              name: nova-etc
        - name: nova-spicehtml5proxy
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-nova-spicehtml5proxy:{{.Values.image_version_nova_spicehtml5proxy}}
          imagePullPolicy: IfNotPresent
          env:
            - name: COMMAND
              value: "nova-spicehtml5proxy"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "nova-api"
          volumeMounts:
            - mountPath: /var/lib/kolla/config_files
              name: nova-etc
      volumes:
        - name: nova-etc
          configMap:
            name: nova-etc
