apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: nova-console
  namespace: {{.Release.Namespace}}
  labels:
    system: openstack
    type: backend
    component: nova
spec:
  tls:
     - secretName: tls-{{include "nova_console_endpoint_host_public" . | replace "." "-" }}
       hosts: [{{include "nova_console_endpoint_host_public" .}}]
  rules:
    - host: {{include "nova_console_endpoint_host_public" .}}
      http:
        paths:
        - path: /
          backend:
            serviceName: nova-console
            servicePort: {{.Values.global.nova_novnc_port_public}}
