kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: nova-console
  labels:
    system: openstack
    type: backend
    component: nova
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: nova-console
  template:
    metadata:
      labels:
        name: nova-console

    spec:
      containers:
        - name: nova-consoleauth
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-nova-consoleauth:{{.Values.image_version_nova_consoleauth}}
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /container.init/nova-consoleauth-start"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "nova-api"
          volumeMounts:
            - mountPath: /nova-etc
              name: nova-etc
            - mountPath: /container.init
              name: container-init
        - name: nova-novncproxy
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-nova-novncproxy:{{.Values.image_version_nova_novncproxy}}
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /container.init/nova-novncproxy-start"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "nova-api"
          volumeMounts:
            - mountPath: /nova-etc
              name: nova-etc
            - mountPath: /container.init
              name: container-init
        - name: nova-spicehtml5proxy
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-nova-spicehtml5proxy:{{.Values.image_version_nova_spicehtml5proxy}}
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /container.init/nova-spicehtml5proxy-start"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "nova-api"
          volumeMounts:
            - mountPath: /nova-etc
              name: nova-etc
            - mountPath: /container.init
              name: container-init

      volumes:
        - name: nova-etc
          configMap:
            name: nova-etc
        - name: container-init
          configMap:
            name: nova-bin
            defaultMode: 0755