apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-etc
  labels:
    system: openstack
    type: configuration
    component: nova

data:
  nova.conf: |
{{ include "nova/templates/etc/_nova.conf.tpl" .| indent 4 }}
  libvirtd.conf: |
{{ include "nova/templates/etc/_libvirtd.conf.tpl" .| indent 4 }}
  logging.conf: |
{{ include "nova/templates/etc/_nova-logging.conf.tpl" .| indent 4 }}