apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-etc
  namespace: {{.Release.Namespace}}
  labels:
    system: openstack
    type: configuration
    component: nova

data:
  nova.conf: |
{{ include "etc/nova.conf" .| indent 4 }}
  libvirtd.conf: |
{{ include "etc/libvirtd.conf" .| indent 4 }}
  logging.conf: |
{{ include "etc/nova-logging.conf" .| indent 4 }}