apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-patches
  labels:
    system: openstack
    type: patches
    component: nova

data:
  vif.diff: |
{{ .Files.Get "patches/vif.diff" | indent 4}}


