apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-patches
  labels:
    system: openstack
    type: patches
    component: nova

data:
  vif.patch: |
{{ .Files.Get "patches/vif.patch" | indent 4}}
  ova-import.patch: |
{{ .Files.Get "patches/ova_import.patch" | indent 4}}
