kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: nova-scheduler
  labels:
    system: openstack
    type: backend
    component: nova
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: nova-scheduler
  template:
    metadata:
      labels:
        name: nova-scheduler
    spec:
      containers:
        - name: nova-scheduler
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-nova-scheduler:{{.Values.image_version_nova_scheduler}}
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /container.init/nova-scheduler-start"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "nova-api,rabbitmq"
          volumeMounts:
            - mountPath: /nova-etc
              name: nova-etc
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: nova-etc
          configMap:
            name: nova-etc
        - name: container-init
          configMap:
            name: nova-bin
            defaultMode: 0755
