kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: neutron-aci-agent
  namespace: {{.Release.Namespace}}
  labels:
    system: openstack
    type: backend
    component: neutron
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: neutron-aci-agent
  template:
    metadata:
      labels:
        name: neutron-aci-agent
      annotations:
        pod.beta.kubernetes.io/hostname:  aci-agent-pet
    spec:
      nodeSelector:
        zone: farm
      containers:
        - name: neutron-aci-agent
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-neutron-server-m3:{{.Values.global.image_version_neutron_server_m3}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - /openstack-kube/openstack-kube/scripts/_container_init
          args:
            - neutron-aci-agent-start
          livenessProbe:
            exec:
              command:
              - /openstack-kube/openstack-kube/scripts/liveness-checks/neutron/service-liveness-check
              - --config-file=/etc/neutron/neutron.conf
              - --config-file=/openstack-kube/openstack-kube/scripts/liveness-checks/neutron/aci-agent-liveness.conf
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 2
          env:
            - name: DEBUG_CONTAINER
              value: "false"
            - name: SENTRY_DSN
              value: "{{ include "sentry_dsn_neutron" . }}"
          volumeMounts:
            - mountPath: /development
              name: development
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /neutron-etc
              name: neutron-etc
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{.Values.global.configuration_repository}}
            revision: {{.Values.global.configuration_revision}}
        - name: development
          persistentVolumeClaim:
            claimName: development-pvclaim
        - name: neutron-etc
          configMap:
            name: neutron-etc
        - name: container-init
          configMap:
            name: neutron-bin

