apiVersion: v1
kind: ConfigMap
metadata:
  name: f5-patches
  labels:
    system: openstack
    type: patches
    component: neutron

data:
  barbican-cert.diff: |
{{ .Files.Get "patches/f5/barbican_cert.diff" | indent 4 }}
  loadbalancer-dbv2.diff: |
{{ .Files.Get "patches/f5/loadbalancer_dbv2.diff" | indent 4 }}
  service-builder.diff: |
{{ .Files.Get "patches/f5/service_builder.diff" | indent 4 }}
  network-helper.diff: |
{{ .Files.Get "patches/f5/network_helper.diff" | indent 4 }}
  keystone.diff: |
{{ .Files.Get "patches/f5/keystone.diff" | indent 4 }}
