kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: neutron-agents-network1
  labels:
    system: openstack
    type: backend
    component: neutron
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:

    metadata:
      labels:
        name: neutron-agents-network1
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"species","value":"network"}]'
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      nodeSelector:
        kubernetes.io/hostname: {{.Values.agent_host1}}
      containers:
        - name: neutron-dhcp-agent
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-neutron-dhcp-agent:{{.Values.image_version_neutron_dhcp_agent}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - bash
          args:
            - /container.init/neutron-dhcp-agent-start
          env:
            - name: SENTRY_DSN
              value: {{include "sentry_dsn_neutron" .}}
          volumeMounts:
            - mountPath: /var/run
              name: run
            - mountPath: /neutron-etc
              name: neutron-etc
            - mountPath: /neutron-patches
              name: neutron-patches
            - mountPath: /container.init
              name: container-init
        - name: neutron-metadata-agent
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-neutron-metadata-agent:{{.Values.image_version_neutron_metadata_agent}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - bash
          args:
            - /container.init/neutron-metadata-agent-start
          env:
            - name: SENTRY_DSN
              value: {{include "sentry_dsn_neutron" .}}

          volumeMounts:
            - mountPath: /var/run
              name: run
            - mountPath: /neutron-etc
              name: neutron-etc
            - mountPath: /container.init
              name: container-init
        - name: neutron-l3-agent
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-neutron-l3-agent:{{.Values.image_version_neutron_l3_agent}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - bash
          args:
            - /container.init/neutron-l3-agent-start
          env:
            - name: SENTRY_DSN
              value: {{include "sentry_dsn_neutron" .}}
          volumeMounts:
            - mountPath: /var/run
              name: run
            - mountPath: /lib/modules
              name: modules
              readOnly: true
            - mountPath: /neutron-etc
              name: neutron-etc
            - mountPath: /container.init
              name: container-init
        - name: neutron-ovs-agent
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-neutron-openvswitch-agent:{{.Values.image_version_neutron_openvswitch_agent}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - bash
          args:
            - /container.init/neutron-ovs-agent-start
          env:
            - name: SENTRY_DSN
              value: {{include "sentry_dsn_neutron" .}}
          volumeMounts:
            - mountPath: /var/run
              name: run
            - mountPath: /lib/modules
              name: modules
              readOnly: true
            - mountPath: /neutron-etc
              name: neutron-etc
            - mountPath: /container.init
              name: container-init

        - name: ovs
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-openvswitch-vswitchd:{{.Values.image_version_neutron_vswitchd}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - bash
          args:
            - /container.init/neutron-ovs-start
          env:
            - name: DEBUG_CONTAINER
              value: "false"
            - name: SENTRY_DSN
              value: {{include "sentry_dsn_neutron" .}}
          volumeMounts:
            - mountPath: /var/run
              name: run
            - mountPath: /lib/modules
              name: modules
              readOnly: true
            - mountPath: /container.init
              name: container-init
        - name: ovs-db
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-openvswitch-db-server:{{.Values.image_version_neutron_vswitchdb}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - bash
          args:
            - /container.init/neutron-ovs-db-start
          volumeMounts:
            - mountPath: /lib/modules
              name: modules
            - mountPath: /var/run
              name: run
            - mountPath: /container.init
              name: container-init
      volumes:
        - name : run
          emptyDir:
            medium: Memory
        - name : modules
          hostPath:
            path: /lib/modules
        - name: neutron-etc
          configMap:
            name: neutron-etc
        - name: neutron-patches
          configMap:
            name: neutron-patches
        - name: container-init
          configMap:
            name: neutron-bin
