apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-patches
  labels:
    system: openstack
    type: patches
    component: neutron

data:
  dhcp.diff: |
{{ .Files.Get "patches/dhcp.diff" | indent 4 }}
  dns-integration.diff: |
{{ .Files.Get "patches/dns_integration.diff" | indent 4 }}


