kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: neutron-server
  labels:
    system: openstack
    type: api
    component: neutron
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: neutron-server
  template:
    metadata:
      labels:
        name: neutron-server
    spec:
      nodeSelector:
        zone: farm
      containers:
        - name: neutron-server
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-neutron-server-m3:{{.Values.image_version_neutron_server_m3}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - /openstack-kube/openstack-kube/scripts/_container_init
          args:
            - neutron-server-start
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.global.neutron_api_port_internal}}
            initialDelaySeconds: 60
            timeoutSeconds: 5
          env:
            - name: DEBUG_CONTAINER
              value: "false"
            - name: STATSD_HOST
              value: "localhost"
            - name: STATSD_PORT
              value: "9125"
            - name: SENTRY_DSN
              value: {{include "sentry_dsn_neutron" .}}
          ports:
            - name: neutron-api
              containerPort: {{.Values.global.neutron_api_port_internal}}
          volumeMounts:
            - mountPath: /development
              name: development
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /neutron-etc
              name: neutron-etc
            - mountPath: /neutron-patches
              name: neutron-patches
            - mountPath: /f5-patches
              name: f5-patches
            - mountPath: /cisco-patches
              name: cisco-patches
            - mountPath: /container.init
              name: container-init
        - name: statsd
          image: prom/statsd-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: metrics
              containerPort: {{.Values.port_metrics}}
      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{.Values.global.configuration_repository}}
            revision: {{.Values.global.configuration_revision}}
        - name: neutron-etc
          configMap:
            name: neutron-etc
        - name: neutron-patches
          configMap:
            name: neutron-patches
        - name: f5-patches
          configMap:
            name: f5-patches
        - name: cisco-patches
          configMap:
            name: cisco-patches
        - name: development
          persistentVolumeClaim:
            claimName: development-pvclaim
        - name: container-init
          configMap:
            name: neutron-bin
