# Default values for nova.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  image_namespace: REQUIRED
  image_repository: REQUIRED
  nova_api_port_admin: '8774'
  nova_api_port_internal: '8774'
  nova_api_port_public: '443'
  nova_metadata_port_internal: '8775'
  nova_novnc_port_public: '443'
  nova_spicehtml5_port_public: '6082'

debug: "True"

db_name: nova
db_user: nova
db_password: DEFINED-IN-REGION-CHART

api_db_name: nova_api
api_db_user: nova_api
api_db_password: DEFINED-IN-REGION-CHART

port_metrics: '9102'

sentry_dsn_key: DEFINE_IN_REGION_CHART

image_version_nova_api_m3: DEFINED-IN-REGION-CHART
image_version_nova_compute_m3: DEFINED-IN-REGION-CHART
image_version_nova_libvirt: DEFINED-IN-REGION-CHART
image_version_nova_conductor: DEFINED-IN-REGION-CHART
image_version_nova_consoleauth: DEFINED-IN-REGION-CHART
image_version_nova_novncproxy: DEFINED-IN-REGION-CHART
image_version_nova_spicehtml5proxy: DEFINED-IN-REGION-CHART
image_version_nova_scheduler: DEFINED-IN-REGION-CHART

postgres:
  name: nova