apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-bin
  labels:
    system: openstack
    type: configuration
    component: messaging

data:
  rabbitmq-start: |
{{ include "bin/rabbitmq-start" .| indent 4 }}
  common.sh: |
{{ include "common.sh" .| indent 4 }}


