apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-bin
  labels:
    system: openstack
    type: configuration
    component: messaging

data:
  rabbitmq-start: |
{{ tuple "bin/_rabbitmq-start.tpl" . | include "template" | indent 4 }}
  common.sh: |
{{ include "common.sh" .| indent 4 }}


