apiVersion: v1
kind: ConfigMap
metadata:
  name: horizon-etc
  labels:
    system: openstack
    type: configuration
    component: horizon

data:
  local-settings: |
{{ tuple "etc/_local-settings.tpl" . | include "template" | indent 4 }}
  policyv3.json: |
{{ tuple "etc/_horizon-policyv3.json.tpl" . | include "template" | indent 4 }}
  horizon.conf: |
{{ tuple "etc/_horizon.conf.tpl" . | include "template" | indent 4 }}

