apiVersion: v1
kind: ConfigMap
metadata:
  name: horizon-etc
  labels:
    system: openstack
    type: configuration
    component: horizon

data:
  local-settings: |
{{ include "horizon/templates/etc/_local-settings.tpl" .| indent 4 }}
  policyv3.json: |
{{ include "horizon/templates/etc/_horizon-policyv3.json.tpl" .| indent 4 }}
  horizon.conf: |
{{ include "horizon/templates/etc/horizon.conf.tpl" .| indent 4 }}
