apiVersion: v1
kind: ConfigMap
metadata:
  name: horizon-etc
  labels:
    system: openstack
    type: configuration
    component: horizon

data:
  local-settings: |
{{ include (print .Template.BasePath "/etc/_local-settings.tpl") . | indent 4 }}
  keystone-policy.json: |
{{ include (print .Template.BasePath "/etc/_horizon-keystone-policy.json.tpl") . | indent 4 }}
  nova-policy.json: |
{{ include (print .Template.BasePath "/etc/_horizon-nova-policy.json.tpl") . | indent 4 }}
  horizon.conf: |
{{ include (print .Template.BasePath "/etc/_horizon.conf.tpl") . | indent 4 }}
