# Default values for 
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

global:
  glance_api_port_internal: REQUIRED 
  image_namespace: REQUIRED
  image_repository: REQUIRED

image_version_glance_api_m3: REQUIRED
image_version_glance_registry: REQUIRED

debug: "True"
db_name: glance
db_user: glance
db_password: DEFINE_IN_REGION_CHART

port_metrics: '9102'
sentry_dsn_key: DEFINE_IN_REGION_CHART

default_store: DEFINE_IN_REGION_CHART
swift_domain: DEFINE_IN_REGION_CHART
swift_project: DEFINE_IN_REGION_CHART
swift_multi_tenant: DEFINE_IN_REGION_CHART

postgres:
  name: glance
