# Default values for global.postgres_
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: DEFINED-IN-COMPONENT-CHART
user: postgres
password: DEFINED-IN-REGION-CHART
port_public: '5432'
port_private: '5432'
port_metrics: '9113'


